auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: sealhuang's blog
url: http://sealhuang.github.io
feed: /atom.xml
author_info: <a href="http://sealhuang.github.io/">SealHuang</a>
